import Header from "@/components/Header";
import AuthProvider from "@/contexts/AuthProvider";
import UpdateProvider from "@/contexts/UpdateContext";
import ZiplineProvider from "@/contexts/ZiplineProvider";
import BiometricAuthenticationPage from "@/pages/biometricAuth";
import NoInternetPage from "@/pages/noInternet";
import { styles } from "@/styles/sentry";
import NetInfo from "@react-native-community/netinfo";
import * as Sentry from "@sentry/react-native";
import * as ImagePicker from "expo-image-picker";
import { Slot, useRouter } from "expo-router";
import { ShareIntentProvider } from "expo-share-intent";
import { StatusBar } from "expo-status-bar";
import { useEffect, useState } from "react";
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { KeyboardProvider } from "react-native-keyboard-controller";
import { Host } from "react-native-portalize";
import { SafeAreaView } from "react-native-safe-area-context";

// Generated by @sentry/wizard
Sentry.init({
	dsn: "https://ae87650be727030f6391c066d97ee51c@o755497.ingest.us.sentry.io/4510311131316224",

	sendDefaultPii: true,

	enableLogs: true,

	replaysSessionSampleRate: 0.1,
	replaysOnErrorSampleRate: 1,

	integrations: [
		Sentry.mobileReplayIntegration(),
		Sentry.feedbackIntegration({
			// @ts-expect-error
			imagePicker: ImagePicker,

			enableScreenshot: true,
			enableTakeScreenshot: true,

			successMessageText: "Thank you for your feedback!",

			messageLabel: "Feedback",
			submitButtonLabel: "Send Feedback",

			messagePlaceholder: "Type your feedback here...",
			emailPlaceholder: "your.email@gmail.com",
			formTitle: "Feedback",
			screenshotButtonOptions: {
				styles: {
					triggerButton: styles.screenshotTriggerButton,
					triggerText: styles.screenshotTriggerText,
				},
			},

			buttonOptions: {
				styles: {
					triggerButton: styles.reportTriggerButton,
					triggerText: styles.reportTriggerText,
				},
			},

			styles: {
				cancelButton: styles.cancelButton,
				cancelText: styles.cancelText,
				submitButton: styles.submitButton,
				submitText: styles.submitText,
				takeScreenshotButton: styles.takeScreenshotButton,
				takeScreenshotText: styles.takeScreenshotText,
				screenshotButton: styles.screenshotButton,
				screenshotText: styles.screenshotText,
				screenshotContainer: styles.screenshotContainer,
				input: styles.input,
				label: styles.label,
			},

			colorScheme: "dark",
			themeDark: {
				background: "#0c101c",
			},
		}),
		Sentry.consoleLoggingIntegration({
			levels: ["log", "warn", "error", "info", "debug"],
		}),
	],
});

export default Sentry.wrap(function Layout() {
	const router = useRouter();
	const [hasInternet, setHasInternet] = useState<boolean>(false);

	useEffect(() => {
		NetInfo.fetch().then((state) => {
			setHasInternet(state.isConnected || false);
		});

		const unsubscribe = NetInfo.addEventListener((state) => {
			setHasInternet(state.isConnected || false);
		});

		return () => {
			unsubscribe();
		};
	}, []);

	return (
		<ShareIntentProvider
			options={{
				scheme: "zipline",
				// debug: __DEV__,
				resetOnBackground: true,
				onResetShareIntent: () =>
					router.replace({
						pathname: "/",
					}),
			}}
		>
			<StatusBar style="light" />

			<SafeAreaView style={{ flex: 1, backgroundColor: "#0c101c" }}>
				<KeyboardProvider>
					<GestureHandlerRootView>
						<AuthProvider>
							<ZiplineProvider>
								<UpdateProvider>
									<Host>
										<Header>
											<Slot />

											<BiometricAuthenticationPage />

											{!hasInternet && <NoInternetPage />}
										</Header>
									</Host>
								</UpdateProvider>
							</ZiplineProvider>
						</AuthProvider>
					</GestureHandlerRootView>
				</KeyboardProvider>
			</SafeAreaView>
		</ShareIntentProvider>
	);
});
