import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	screenshotTriggerButton: {
		borderRadius: 6,
		boxShadow: "0 4px 8px rgba(0, 0, 0, 0.125)",
		height: 40,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
		paddingHorizontal: 16,
		paddingVertical: 4,
		gap: 6,
		backgroundColor: "#323ea8",
		marginVertical: 10,
	},
	screenshotTriggerText: {
		textAlign: "center",
		fontWeight: "bold",
		color: "#ffffff",
	},
	reportTriggerButton: {
		borderRadius: 6,
		boxShadow: "0 4px 8px rgba(0, 0, 0, 0.125)",
		height: 40,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
		paddingHorizontal: 16,
		paddingVertical: 4,
		gap: 6,
		backgroundColor: "#323ea8",
		marginVertical: 10,
	},
	reportTriggerText: {
		textAlign: "center",
		fontWeight: "bold",
		color: "#ffffff",
	},
	cancelButton: {
		borderRadius: 6,
		boxShadow: "0 4px 8px rgba(0, 0, 0, 0.125)",
		height: 40,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
		paddingHorizontal: 4,
		paddingVertical: 2,
		gap: 6,
		backgroundColor: "#CF4238",
	},
	cancelText: {
		textAlign: "center",
		fontWeight: "bold",
		color: "#ffffff",
	},
	submitButton: {
		borderRadius: 6,
		boxShadow: "0 4px 8px rgba(0, 0, 0, 0.125)",
		height: 40,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
		paddingHorizontal: 4,
		paddingVertical: 2,
		gap: 6,
		backgroundColor: "#323ea8",
		marginVertical: 10,
	},
	submitText: {
		textAlign: "center",
		fontWeight: "bold",
		color: "#ffffff",
	},
	takeScreenshotButton: {
		borderRadius: 6,
		boxShadow: "0 4px 8px rgba(0, 0, 0, 0.125)",
		height: 40,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
		paddingHorizontal: 4,
		paddingVertical: 2,
		gap: 6,
		backgroundColor: "#323ea8",
		marginBottom: 10,
		marginTop: -10,
	},
	takeScreenshotText: {
		textAlign: "center",
		fontWeight: "bold",
		color: "#ffffff",
	},
	screenshotButton: {
		borderRadius: 6,
		boxShadow: "0 4px 8px rgba(0, 0, 0, 0.125)",
		height: 40,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
		paddingHorizontal: 4,
		paddingVertical: 2,
		gap: 6,
		backgroundColor: "#323ea8",
		flex: 1,
	},
	screenshotText: {
		textAlign: "center",
		fontWeight: "bold",
		color: "#ffffff",
	},
	screenshotContainer: {
		marginTop: 10,
		alignItems: "center",
		flexDirection: "row",
		width: "100%",
		marginBottom: 20,
	},
	input: {
		borderWidth: 2,
		borderColor: "#222c47",
		color: "white",
		height: 40,
		paddingHorizontal: 10,
		fontSize: 15,
		borderRadius: 6,
		paddingTop: 0,
		paddingBottom: 0,
	},
    label: {
		marginTop: 5,
		marginBottom: 5,
		fontSize: 18,
		fontWeight: "bold",
		color: "white",
	}
});
